### ISSUE TITLE
PropertyCreators return null if the json value of the property is null.

### ISSUE THREAD

**Issue by cguckes** [joffrey-bion/fx-gson#5]
It would be great, if they returned an empty property by default or more flexible: make it configurable.

I currently use this code to get around the issue:

    LongProperty myReturn;
    if (jsonReader.peek() == JsonToken.NULL) {
        jsonReader.nextNull();
        myReturn = new SimpleLongProperty();
    }
    else {
        myReturn = new SimpleLongProperty(jsonReader.nextLong());
    }
    return myReturn;

**Comment by joffrey-bion** [comment]
But how can you get a null value out of a LongProperty in the first place?

**Comment by cguckes** [comment]
It's not so much manual tampering that could create these values but the structure of the REST-API delivering the JSON. I'm using Gson to access a REST API that isn't generated via Gson. According to the API documentation, there are some answers that contain data that looks like this:

    {
        "number": null
    }

When I convert this into a LongProperty or an IntegerProperty via Gson, the PropertyObject is explicitly set to null. I would like to get an empty LongProperty, because if the null-field is missing entirely, this is what I get. It's therefore much easier for me as the user, if I get an empty Property instead of a NullPointer. In my current implementation (an API facade of 3k lines of code) saves me about 1k NotNull checks, because I only need to check the property's content and not the property itself.

**Comment by joffrey-bion** [comment]
I see, the use case sounds reasonable.
I didn't think of a usage where you only use deserialization.

**Comment by joffrey-bion** [comment]
I added 2 things:
1. a clear exception for null values on primitives
2. a configurable fallback to default empty property (for convenience)

That being said, the absence of key in the JSON and the presence of a key with a null value are 2 different things and should be treated as such.

# Regarding the absence of key

If the key is absent, you can still get a non-null property if you initialize it directly in the final fields or in a no-arg constructor:

    public class MyClass {
        private final IntegerProperty number = new SimpleIntegerProperty();
    }

Or:

    public class MyClass {
        private final IntegerProperty number;
        public MyClass() {
            number = new SimpleIntegerProperty();
        }
    }

Gson calls the no-arg constructor if it finds one.

# Regarding the null value

If you need to handle null values, then maybe you should use `ObjectProperty<Long>` instead of `LongProperty`. Silently falling back to a default "0" doesn't look right, you should manually fallback with a warning or something.
